---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - image: sandbox-hello:0.0.6
        imagePullPolicy: IfNotPresent
        name: hello
        command:
          - /bin/sh
        args:
          - -c
          - /app/hello server --address :5555
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  ports:
    - name: grpc
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app.kubernetes.io/name: hello
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: hello.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-svc
                port:
                  number: 5555