---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-deployment
spec:
  selector:
    matchLabels:
      app: hello-nginx-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-nginx-deployment
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: hello.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-nginx-svc
                port:
                  number: 80
  tls:
    - secretName: hello-tls-secret
      hosts:
        - hello.example.com